# Generated by Django 4.0.2 on 2023-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_alter_sample_table_price_banking_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking',
            name='bd_bnk_det',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='banking',
            name='mail_addr',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
