# Generated by Django 4.0.2 on 2023-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_rename_currency_chart_of_account_credit_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_account',
            name='attachment',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='chart_of_account',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
